In [7]:
import numpy as np
import scipy

xs = np.empty(int(1e4))

%timeit scipy.ndimage.shift(xs, 3, order=0, mode='constant', cval=np.NaN, prefilter=False)

161 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
def shift(xs, n):
    if n >= 0:
        return np.r_[np.full(n, np.nan), xs[:-n]]
    else:
        return np.r_[xs[-n:], np.full(-n, np.nan)]

%timeit shift(xs, 4)

15.5 µs ± 244 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
np.empty((int(1e2), int(1e2)))[tuple([np.s_[1:], np.s_[1:]])].shape

TypeError: tuple expected at most 1 argument, got 2

In [16]:
tuple(a for a in [1,2])

(1, 2)

In [34]:
import numpy as np

# https://stackoverflow.com/a/27087513/11934495
def _shift(a, offsets, fill_value=np.nan):
    _mom = lambda s: max(0, s)
    _non = lambda s: s if s < 0 else None

    res = np.full_like(a, fill_value=fill_value)
    res[tuple(np.s_[_mom(o):_non(o)] for o in offsets)] \
        = a[tuple(np.s_[_mom(-o):_non(-o)] for o in offsets)]

    return res

#%timeit _shift(np.random.rand(int(1e3), int(1e4)), offsets=(10, 10))
%timeit _shift(np.random.rand(3840, 2160), offsets=(10, 10))

160 ms ± 2.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [79]:
a = np.random.rand(5, 5)
_shift(a, offsets=(-1, -1)) #- _shift(a, offsets=(-1, 0))

array([[0.48487268, 0.99210684, 0.00391865, 0.46874951,        nan],
       [0.85019869, 0.17476457, 0.3389439 , 0.50691623,        nan],
       [0.13689083, 0.91014512, 0.39802933, 0.22023545,        nan],
       [0.87027076, 0.23352419, 0.44286331, 0.6512303 ,        nan],
       [       nan,        nan,        nan,        nan,        nan]])

In [3]:
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9], [3, 7,9]])[::-1,:]
print(x)
print(x[::-1,:])

[[3 7 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 7 9]]


In [88]:
np.array([0.]) == 0

array([ True])

In [87]:
a[1:, 1:] - a[1:, 0:-1]

array([[ 0.21226666,  0.50723416, -0.98818819,  0.46483086],
       [ 0.42427005, -0.67543411,  0.16417933,  0.16797232],
       [-0.4625298 ,  0.77325428, -0.51211578, -0.17779388],
       [-0.00881306, -0.63674657,  0.20933912,  0.20836698]])

In [80]:
_shift(a, offsets=(-1, 0))

array([[0.27260602, 0.48487268, 0.99210684, 0.00391865, 0.46874951],
       [0.42592864, 0.85019869, 0.17476457, 0.3389439 , 0.50691623],
       [0.59942063, 0.13689083, 0.91014512, 0.39802933, 0.22023545],
       [0.87908382, 0.87027076, 0.23352419, 0.44286331, 0.6512303 ],
       [       nan,        nan,        nan,        nan,        nan]])

In [46]:
import typing
class Range(typing.NamedTuple):
    min: typing.Any
    max: typing.Any

    def has(self, n) -> bool:
        return self.min <= n and n <= self.max

    @property
    def set(self): return self._replace

Range(10, 100).has(90)
Range(10, 100).set(min=1)

Range(min=1, max=100)

In [74]:
import random
random.choice(range(1, 10, step=2))

TypeError: range() takes no keyword arguments

In [61]:
range(**range(1, 10).__dict__)

AttributeError: 'range' object has no attribute '__dict__'

In [59]:
type(range(1, 10))

range

In [75]:
10 in range(1., 10000000.)

TypeError: 'float' object cannot be interpreted as an integer

In [57]:
%timeit 2 in range(1, 10000000000000000000000, 5)

192 ns ± 1.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [58]:
%timeit 2 in range(1, 10, 5)

132 ns ± 2.45 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [50]:
range(1, 100).start

1

In [28]:
non = lambda s: s if s<0 else None
mom = lambda s: max(0,s)

ox, oy = 100, 20

lena = np.random.rand(int(1e1), int(1e1))
shift_lena = np.zeros_like(lena)
shift_lena[mom(oy):non(oy), mom(ox):non(ox)] = lena[mom(-oy):non(-oy), mom(-ox):non(-ox)]
shift_lena

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.random.rand(int(1e1), int(1e1))

array([[0.14722417, 0.65187387, 0.2182883 , 0.96870189, 0.16140282,
        0.49674699, 0.19216196, 0.80956324, 0.1634241 , 0.02985771],
       [0.57946233, 0.44927198, 0.77446557, 0.28985117, 0.51271813,
        0.71089524, 0.08477589, 0.30820718, 0.59274624, 0.01339266],
       [0.12683431, 0.90358764, 0.89757084, 0.21345632, 0.76391804,
        0.81595428, 0.00497499, 0.26151264, 0.05902862, 0.68235074],
       [0.53531016, 0.28756075, 0.32437459, 0.7269367 , 0.3978504 ,
        0.12553503, 0.263205  , 0.88904344, 0.48662597, 0.90631622],
       [0.9434918 , 0.65483762, 0.19021461, 0.31227834, 0.03908298,
        0.74431537, 0.62361831, 0.68348902, 0.37665268, 0.17147724],
       [0.63448048, 0.22508845, 0.90497971, 0.43762653, 0.17178309,
        0.20864504, 0.30874608, 0.79572176, 0.66382593, 0.35957342],
       [0.03684169, 0.87889069, 0.47262484, 0.48845591, 0.34652259,
        0.08905608, 0.38723422, 0.60764266, 0.96394283, 0.00850713],
       [0.40568912, 0.79912775, 0.6753114